Add configuration files for JDK18
ibmruntimes/ci-jenkins-pipelines pull request #10
Opened 2021-09-10 17:40 UTC by vsebe

Add jdk18 configuration files for upstream and downstream pipelines.

Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

2021-09-10 17:40 UTC, vsebe commented
@AdamBrousseau fyi

2021-09-10 17:46 UTC, AdamBrousseau requested changes
If we aren't ready/able to simply merge from upstream, can we cherry-pick the original commit and then make modifications on top of it? We don't need the XL specs anymore.

2021-09-10 19:26 UTC, vsebe commented
It is close to the original commit since I started with it. I cleaned XL platforms.

2021-09-15 05:30 UTC, AdamBrousseau approved these changes

2021-09-15 05:30 UTC, merged